dropna & fillna

In [28]:
import pandas as pd
var = pd.read_csv("C:\\Users\\HP Pavilion\\OneDrive\\Desktop\\Portfolio\\Python\\Pandas\\SalesReport2.csv")
var

              Product Customer     Qtr 1     Qtr 2       Qtr 3     Qtr 4
0        Alice Mutton    ANTON     $-     $702.00        $-        $-
1        Alice Mutton    BERGS  $312.00      $-          $-        $-
2        Alice Mutton    BOLID     $-          NaN       $-          NaN
3        Alice Mutton    BOTTM       NaN     $-          $-        $-
4        Alice Mutton    ERNSH       NaN     $-          $-          NaN
5        Alice Mutton    GODOS     $-     $280.80        $-        $-
6        Alice Mutton    HUNGC   $62.40      $-          $-        $-
7        Alice Mutton    PICCO     $-          NaN    $936.00      $-
8        Alice Mutton    RATTC     $-     $592.80        $-        $-
9        Alice Mutton    REGGC     $-        $-          $-     $741.00
10       Alice Mutton    SAVEA     $-        $-            NaN  $789.75
11       Alice Mutton    SEVES       NaN  $877.50        $-        $-
12       Alice Mutton    WHITC     $-        $-          $-     $780.00
13      Aniseed Syrup    ALFKI     $-        $-          $-      $60.00
14      Aniseed Syrup    BOTTM     $-          NaN       $-     $200.00
15      Aniseed Syrup    ERNSH     $-        $-          $-     $180.00
16      Aniseed Syrup    LINOD  $544.00      $-          $-        $-
17      Aniseed Syrup    QUICK     $-     $600.00        $-        $-
18      Aniseed Syrup    VAFFE     $-        $-       $140.00        NaN
19   Boston Crab Meat    ANTON     $-     $165.60        $-        $-
20                NaN      NaN       NaN       NaN         NaN       NaN
21   Boston Crab Meat    BONAP     $-     $248.40     $524.40      $-
22   Boston Crab Meat    BOTTM  $551.25      $-          $-        $-
23   Boston Crab Meat    BSBEV  $147.00      $-          $-        $-
24   Boston Crab Meat    FRANS     $-        $-          $-      $18.40
25   Boston Crab Meat    HILAA     $-      $92.00   $1,104.00      $-
26   Boston Crab Meat    LAZYK  $147.00      $-          $-        $-
27   Boston Crab Meat    LEHMS     $-     $515.20        $-        $-
28   Boston Crab Meat    MAGAA     $-        $-          $-      $55.20
29   Boston Crab Meat    OTTIK     $-        $-       $368.00      $-
30   Boston Crab Meat    PERIC  $308.70      $-          $-        $-
31   Boston Crab Meat    QUEEN   $26.46      $-       $419.52   $110.40
32   Boston Crab Meat    QUICK     $-        $-     $1,223.60      $-
33   Boston Crab Meat    RANCH  $294.00      $-          $-        $-
34   Boston Crab Meat    SAVEA     $-        $-       $772.80   $736.00
35   Boston Crab Meat    TRAIH     $-      $36.80        $-        $-
36   Boston Crab Meat    VAFFE  $294.00      $-          $-     $736.00
37  Camembert Pierrot    ANATR     $-        $-       $340.00      $-
38  Camembert Pierrot    AROUT     $-        $-          $-     $510.00
39  Camembert Pierrot    BERGS     $-        $-       $680.00      $-

In [9]:
var.dropna()

              Product Customer     Qtr 1     Qtr 2       Qtr 3     Qtr 4
0        Alice Mutton    ANTON     $-     $702.00        $-        $-
1        Alice Mutton    BERGS  $312.00      $-          $-        $-
5        Alice Mutton    GODOS     $-     $280.80        $-        $-
6        Alice Mutton    HUNGC   $62.40      $-          $-        $-
8        Alice Mutton    RATTC     $-     $592.80        $-        $-
9        Alice Mutton    REGGC     $-        $-          $-     $741.00
12       Alice Mutton    WHITC     $-        $-          $-     $780.00
13      Aniseed Syrup    ALFKI     $-        $-          $-      $60.00
15      Aniseed Syrup    ERNSH     $-        $-          $-     $180.00
16      Aniseed Syrup    LINOD  $544.00      $-          $-        $-
17      Aniseed Syrup    QUICK     $-     $600.00        $-        $-
19   Boston Crab Meat    ANTON     $-     $165.60        $-        $-
21   Boston Crab Meat    BONAP     $-     $248.40     $524.40      $-
22   Boston Crab Meat    BOTTM  $551.25      $-          $-        $-
23   Boston Crab Meat    BSBEV  $147.00      $-          $-        $-
24   Boston Crab Meat    FRANS     $-        $-          $-      $18.40
25   Boston Crab Meat    HILAA     $-      $92.00   $1,104.00      $-
26   Boston Crab Meat    LAZYK  $147.00      $-          $-        $-
27   Boston Crab Meat    LEHMS     $-     $515.20        $-        $-
28   Boston Crab Meat    MAGAA     $-        $-          $-      $55.20
29   Boston Crab Meat    OTTIK     $-        $-       $368.00      $-
30   Boston Crab Meat    PERIC  $308.70      $-          $-        $-
31   Boston Crab Meat    QUEEN   $26.46      $-       $419.52   $110.40
32   Boston Crab Meat    QUICK     $-        $-     $1,223.60      $-
33   Boston Crab Meat    RANCH  $294.00      $-          $-        $-
34   Boston Crab Meat    SAVEA     $-        $-       $772.80   $736.00
35   Boston Crab Meat    TRAIH     $-      $36.80        $-        $-
36   Boston Crab Meat    VAFFE  $294.00      $-          $-     $736.00
37  Camembert Pierrot    ANATR     $-        $-       $340.00      $-
38  Camembert Pierrot    AROUT     $-        $-          $-     $510.00
39  Camembert Pierrot    BERGS     $-        $-       $680.00      $-

In [15]:
#var.dropna(axis=1) # 1 for column and 0 for row

In [14]:
#var.dropna(how="all")    #here when we use any it will remove all the NA but all will remove only which have all row index NA

In [18]:
var.dropna(subset=["Qtr 2"])

              Product Customer     Qtr 1     Qtr 2       Qtr 3     Qtr 4
0        Alice Mutton    ANTON     $-     $702.00        $-        $-
1        Alice Mutton    BERGS  $312.00      $-          $-        $-
3        Alice Mutton    BOTTM       NaN     $-          $-        $-
4        Alice Mutton    ERNSH       NaN     $-          $-          NaN
5        Alice Mutton    GODOS     $-     $280.80        $-        $-
6        Alice Mutton    HUNGC   $62.40      $-          $-        $-
8        Alice Mutton    RATTC     $-     $592.80        $-        $-
9        Alice Mutton    REGGC     $-        $-          $-     $741.00
10       Alice Mutton    SAVEA     $-        $-            NaN  $789.75
11       Alice Mutton    SEVES       NaN  $877.50        $-        $-
12       Alice Mutton    WHITC     $-        $-          $-     $780.00
13      Aniseed Syrup    ALFKI     $-        $-          $-      $60.00
15      Aniseed Syrup    ERNSH     $-        $-          $-     $180.00
16      Aniseed Syrup    LINOD  $544.00      $-          $-        $-
17      Aniseed Syrup    QUICK     $-     $600.00        $-        $-
18      Aniseed Syrup    VAFFE     $-        $-       $140.00        NaN
19   Boston Crab Meat    ANTON     $-     $165.60        $-        $-
21   Boston Crab Meat    BONAP     $-     $248.40     $524.40      $-
22   Boston Crab Meat    BOTTM  $551.25      $-          $-        $-
23   Boston Crab Meat    BSBEV  $147.00      $-          $-        $-
24   Boston Crab Meat    FRANS     $-        $-          $-      $18.40
25   Boston Crab Meat    HILAA     $-      $92.00   $1,104.00      $-
26   Boston Crab Meat    LAZYK  $147.00      $-          $-        $-
27   Boston Crab Meat    LEHMS     $-     $515.20        $-        $-
28   Boston Crab Meat    MAGAA     $-        $-          $-      $55.20
29   Boston Crab Meat    OTTIK     $-        $-       $368.00      $-
30   Boston Crab Meat    PERIC  $308.70      $-          $-        $-
31   Boston Crab Meat    QUEEN   $26.46      $-       $419.52   $110.40
32   Boston Crab Meat    QUICK     $-        $-     $1,223.60      $-
33   Boston Crab Meat    RANCH  $294.00      $-          $-        $-
34   Boston Crab Meat    SAVEA     $-        $-       $772.80   $736.00
35   Boston Crab Meat    TRAIH     $-      $36.80        $-        $-
36   Boston Crab Meat    VAFFE  $294.00      $-          $-     $736.00
37  Camembert Pierrot    ANATR     $-        $-       $340.00      $-
38  Camembert Pierrot    AROUT     $-        $-          $-     $510.00
39  Camembert Pierrot    BERGS     $-        $-       $680.00      $-

In [8]:
var.dropna(thresh= 3)

              Product Customer     Qtr 1     Qtr 2       Qtr 3     Qtr 4
0        Alice Mutton    ANTON     $-     $702.00        $-        $-
1        Alice Mutton    BERGS  $312.00      $-          $-        $-
2        Alice Mutton    BOLID     $-          NaN       $-          NaN
3        Alice Mutton    BOTTM       NaN     $-          $-        $-
4        Alice Mutton    ERNSH       NaN     $-          $-          NaN
5        Alice Mutton    GODOS     $-     $280.80        $-        $-
6        Alice Mutton    HUNGC   $62.40      $-          $-        $-
7        Alice Mutton    PICCO     $-          NaN    $936.00      $-
8        Alice Mutton    RATTC     $-     $592.80        $-        $-
9        Alice Mutton    REGGC     $-        $-          $-     $741.00
10       Alice Mutton    SAVEA     $-        $-            NaN  $789.75
11       Alice Mutton    SEVES       NaN  $877.50        $-        $-
12       Alice Mutton    WHITC     $-        $-          $-     $780.00
13      Aniseed Syrup    ALFKI     $-        $-          $-      $60.00
14      Aniseed Syrup    BOTTM     $-          NaN       $-     $200.00
15      Aniseed Syrup    ERNSH     $-        $-          $-     $180.00
16      Aniseed Syrup    LINOD  $544.00      $-          $-        $-
17      Aniseed Syrup    QUICK     $-     $600.00        $-        $-
18      Aniseed Syrup    VAFFE     $-        $-       $140.00        NaN
19   Boston Crab Meat    ANTON     $-     $165.60        $-        $-
21   Boston Crab Meat    BONAP     $-     $248.40     $524.40      $-
22   Boston Crab Meat    BOTTM  $551.25      $-          $-        $-
23   Boston Crab Meat    BSBEV  $147.00      $-          $-        $-
24   Boston Crab Meat    FRANS     $-        $-          $-      $18.40
25   Boston Crab Meat    HILAA     $-      $92.00   $1,104.00      $-
26   Boston Crab Meat    LAZYK  $147.00      $-          $-        $-
27   Boston Crab Meat    LEHMS     $-     $515.20        $-        $-
28   Boston Crab Meat    MAGAA     $-        $-          $-      $55.20
29   Boston Crab Meat    OTTIK     $-        $-       $368.00      $-
30   Boston Crab Meat    PERIC  $308.70      $-          $-        $-
31   Boston Crab Meat    QUEEN   $26.46      $-       $419.52   $110.40
32   Boston Crab Meat    QUICK     $-        $-     $1,223.60      $-
33   Boston Crab Meat    RANCH  $294.00      $-          $-        $-
34   Boston Crab Meat    SAVEA     $-        $-       $772.80   $736.00
35   Boston Crab Meat    TRAIH     $-      $36.80        $-        $-
36   Boston Crab Meat    VAFFE  $294.00      $-          $-     $736.00
37  Camembert Pierrot    ANATR     $-        $-       $340.00      $-
38  Camembert Pierrot    AROUT     $-        $-          $-     $510.00
39  Camembert Pierrot    BERGS     $-        $-       $680.00      $-

In [13]:
#var.fillna({"Product":"Python","Customer":"Manav","Qtr 1":"$10","Qtr 2":"$20"})

In [20]:
#var.fillna(method="ffill") var.fillna(method="bfill") in this we will fill tha nan with the backbward or forward index value

In [19]:
#var.fillna(method="bfill",axis=1)

In [29]:
# var.fillna(12,inplace=True)
# var

In [30]:
var.fillna("python",limit=2)

              Product Customer     Qtr 1     Qtr 2       Qtr 3     Qtr 4
0        Alice Mutton    ANTON     $-     $702.00        $-        $-
1        Alice Mutton    BERGS  $312.00      $-          $-        $-
2        Alice Mutton    BOLID     $-       python       $-       python
3        Alice Mutton    BOTTM    python     $-          $-        $-
4        Alice Mutton    ERNSH    python     $-          $-       python
5        Alice Mutton    GODOS     $-     $280.80        $-        $-
6        Alice Mutton    HUNGC   $62.40      $-          $-        $-
7        Alice Mutton    PICCO     $-       python    $936.00      $-
8        Alice Mutton    RATTC     $-     $592.80        $-        $-
9        Alice Mutton    REGGC     $-        $-          $-     $741.00
10       Alice Mutton    SAVEA     $-        $-         python  $789.75
11       Alice Mutton    SEVES       NaN  $877.50        $-        $-
12       Alice Mutton    WHITC     $-        $-          $-     $780.00
13      Aniseed Syrup    ALFKI     $-        $-          $-      $60.00
14      Aniseed Syrup    BOTTM     $-          NaN       $-     $200.00
15      Aniseed Syrup    ERNSH     $-        $-          $-     $180.00
16      Aniseed Syrup    LINOD  $544.00      $-          $-        $-
17      Aniseed Syrup    QUICK     $-     $600.00        $-        $-
18      Aniseed Syrup    VAFFE     $-        $-       $140.00        NaN
19   Boston Crab Meat    ANTON     $-     $165.60        $-        $-
20             python   python       NaN       NaN      python       NaN
21   Boston Crab Meat    BONAP     $-     $248.40     $524.40      $-
22   Boston Crab Meat    BOTTM  $551.25      $-          $-        $-
23   Boston Crab Meat    BSBEV  $147.00      $-          $-        $-
24   Boston Crab Meat    FRANS     $-        $-          $-      $18.40
25   Boston Crab Meat    HILAA     $-      $92.00   $1,104.00      $-
26   Boston Crab Meat    LAZYK  $147.00      $-          $-        $-
27   Boston Crab Meat    LEHMS     $-     $515.20        $-        $-
28   Boston Crab Meat    MAGAA     $-        $-          $-      $55.20
29   Boston Crab Meat    OTTIK     $-        $-       $368.00      $-
30   Boston Crab Meat    PERIC  $308.70      $-          $-        $-
31   Boston Crab Meat    QUEEN   $26.46      $-       $419.52   $110.40
32   Boston Crab Meat    QUICK     $-        $-     $1,223.60      $-
33   Boston Crab Meat    RANCH  $294.00      $-          $-        $-
34   Boston Crab Meat    SAVEA     $-        $-       $772.80   $736.00
35   Boston Crab Meat    TRAIH     $-      $36.80        $-        $-
36   Boston Crab Meat    VAFFE  $294.00      $-          $-     $736.00
37  Camembert Pierrot    ANATR     $-        $-       $340.00      $-
38  Camembert Pierrot    AROUT     $-        $-          $-     $510.00
39  Camembert Pierrot    BERGS     $-        $-       $680.00      $-